In [1]:
import numpy as np

In [14]:
# Q.1 Convert a 1D array to a 2D array with 2 rows 

arr1 = np.array([0,1,2,3,4,5,6,7])
print(arr1)

arr1.reshape(2,-1)

[0 1 2 3 4 5 6 7]


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
# Q.2  Get the common items between a and b 

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 

np.intersect1d(a,b)

array([2, 4])

In [18]:
# Get all items between 5 and 10 from a. 

a = np.array([2, 6, 1, 9, 10, 3, 27]) 

filtered_values = a[(a >= 5) & (a <= 10)]

print(filtered_values)

[ 6  9 10]


In [ ]:
# Limit the number of items printed in python NumPy array a to a maximum of 6

array = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]) 
np.set_printoptions(threshold=6)
array

[ 0  1  2 ... 12 13 14]
