#### Q.1 How to create an empty and full numpy array 

In [2]:
import numpy as np

empty_array = np.empty((3,3))
print(empty_array)

print()

full_array = np.full((3, 3), 7)
print(full_array)

print()
empty_2 = np.full((2,2),0)
print(empty_2)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 9.09080788e-321]
 [1.17134168e-311 2.00485144e-307 0.00000000e+000]]

[[7 7 7]
 [7 7 7]
 [7 7 7]]

[[0 0]
 [0 0]]


#### Q.2 Create a numpy array filled with zeros 

In [52]:
zeros_array = np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Q.3 Create a numpy array filled with all once

In [57]:
ones_array = np.ones((2,2))
ones_array

array([[1., 1.],
       [1., 1.]])

#### Q.4 Check whether a Numpy array contains specified row 

In [74]:
arr = np.array([[1,2,3],
                [5,6,7]])

check = np.array([1,2,3])

np.any(arr == check)

True

#### Q.5 How to remove rows in numpy array that contain non numeric value 

In [91]:
arr = np.array([[1,2,3,5],
                [5,6,7,8],
                [0.8,'a','b','c']])

def is_numeric(row):
    try:
        np.array(row,dtype=float)  # Try converting row to float
        return True
    except ValueError:
        return False

# Filter numeric rows
filtered_arr = np.array([row for row in arr if is_numeric(row)])

print(filtered_arr)

[['1' '2' '3' '5']
 ['5' '6' '7' '8']]


#### Q.6 Remove single dimensional entreis from the shape of array  

In [41]:
arr = np.array([[[1,2,3]]])

sq = np.squeeze(arr)
print(f"Original Array : \n{arr}")
print(arr.shape)

print(f"Squeeze Array : \n{sq}")
sq.shape

Original Array : 
[[[1 2 3]]]
(1, 1, 3)
Squeeze Array : 
[1 2 3]


(3,)

#### Q.7 Find a number occurrences of sequence in a Numpy array 

#### Q.8 Find the most frequent value in Numpy array

In [65]:
arr = np.array([1,2,2,3,4,5,5,2])

count = np.bincount(arr)
most_frequent = np.argmax(count)
print(most_frequent)

2


#### Q.9 Combining a one and a two - dimensional Numpy Array 

In [109]:
one_dim = np.array([10,20])
two_dim = np.array([[4,5],
                    [7,8],
                    [9,10]])

print(np.row_stack((one_dim,two_dim)))
print()

one_dim = np.array([10,20,30])
two_dim = np.array([[4,5],
                    [7,8],
                    [9,10]])

print(np.column_stack((one_dim,two_dim)))
print()

one_dim = np.array([10,20])
two_dim = np.array([[4,5],
                    [7,8],
                    [9,10]])

# print(one_dim.reshape(-1,1))
print(np.vstack((one_dim, two_dim)))

one_dim = np.array([10,20,30])
two_dim = np.array([[4,5],
                    [7,8],
                    [9,10]])

# print(one_dim.reshape(-1,1))
np.hstack((one_dim.reshape(-1,1), two_dim))

[[10 20]
 [ 4  5]
 [ 7  8]
 [ 9 10]]

[[10  4  5]
 [20  7  8]
 [30  9 10]]

[[10 20]
 [ 4  5]
 [ 7  8]
 [ 9 10]]


array([[10,  4,  5],
       [20,  7,  8],
       [30,  9, 10]])

#### Q.10 How to build an array of all combinations of two Numpy arrays?

In [115]:
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
g1,g2 = np.meshgrid(arr1,arr2)

combination = np.column_stack([g1.ravel(),g2.ravel()])
print(combination)

[[10  1]
 [20  1]
 [30  1]
 [10  2]
 [20  2]
 [30  2]
 [10  3]
 [20  3]
 [30  3]
 [10  4]
 [20  4]
 [30  4]
 [10  5]
 [20  5]
 [30  5]
 [10  6]
 [20  6]
 [30  6]
 [10  7]
 [20  7]
 [30  7]
 [10  8]
 [20  8]
 [30  8]
 [10  9]
 [20  9]
 [30  9]
 [10 10]
 [20 10]
 [30 10]]


### Numpy array Operations 

In [ ]:
# Functions 1 : np.Concatenate
# Work :
# Concatenate is combine two numpy array according to row and column based on set of 
# both matrix 

# Example 1: 
arr1 = [[1],
        [3]]


arr2 = [[5,6],
        [7,8]]

print("Row wise: \n",np.concatenate((arr1,arr2),axis=1),"\n")

# Example 2: 
arr1 = [[1,2],
        [3,4]]


arr2 = [[5,6],
        [7,8]]

print("Row wise:\n",np.concatenate((arr1,arr2),axis=1),"\n")

# Example 3:
arr1 = [[1,2],
        [3,4]]


arr2 = [[5,6],
        [7,8]]

print("Column wise:\n",np.concatenate((arr1,arr2),axis=0))


Row wise: 
 [[1 5 6]
 [3 7 8]] 

Row wise:
 [[1 2 5 6]
 [3 4 7 8]] 

Column wise:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [208]:
# Function 2 : add.reduce()
# Work :
# here we use np.add.reduce function to perform element wise addition, by using reduce funciton 
# we can do that in easy way and here we can also mention specific row as 1 and column as 0
# so, outcomes according to the requirnment 

# Example 1: 
a = np.arange(9).reshape(3,3)
print(a,"\n")

print("Total number of addition :\n",np.add.reduce(a, (0,1)),"\n")

# Example 2:
a = np.arange(9).reshape(3,3)
print("By default column  Wise\n",np.add.reduce(a),"\n")

# Example 3:
a = np.arange(9).reshape(3,3)
print("Row wise\n",np.add.reduce(a,axis=1),"\n")


[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Total number of addition :
 36 

By default column  Wise
 [ 9 12 15] 

Row wise
 [ 3 12 21] 



In [214]:
# Function 3: Linear Algebra 
# work :
# NumPy provides several linear algebra functions, mainly through the numpy.linalg module. These functions help perform 
# matrix operations, solving equations, determinants, and more.

#Example 1:
# dot function perfor matrix multiplication between two matrix 

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result1 = np.dot(A, B)

# result2 = np.matmul(A, B)
print(result1,"\n")


# Example 2: 
# det function is find determine of matrix 
result1 = np.linalg.det(A)
print(result1,"\n")

# Example 3:
# The Euclidean norm (or L2 norm) is the square root of the sum of squared values.
# (Computed as √(3² + 4²) = √9 + 16 = √25 = 5)

vector = np.array([3, 4])
norm_value = np.linalg.norm(vector)

print(norm_value,"\n")



[[19 22]
 [43 50]] 

-2.0000000000000004 

5.0 



In [ ]:
# Function 4: numpy.fft()
# The Fast Fourier Transform (FFT) is an algorithm to compute the Discrete Fourier Transform (DFT) and its inverse efficiently. 
# It is widely used in signal processing, image processing, and scientific computing.

# Example 1: 
signal = np.array([1, 2, 1])

fft_result = np.fft.fft(signal)

print("FFT Result:", fft_result,"\n")

# Example 2: 
# Compute the inverse FFT
inverse_fft = np.fft.ifft(fft_result)

print("Recovered Signal:", inverse_fft.real,"\n")  # Use .real to remove small imaginary parts

# Example 3:
# Define a simple input array
arr = np.array([1, 2, 3, 4])

# Compute the FFT
fft_result = np.fft.fft(arr)

print("FFT Result:", fft_result)



FFT Result: [ 4. +0.j        -0.5-0.8660254j -0.5+0.8660254j] 

Recovered Signal: [1. 2. 1.] 

FFT Result: [10.+0.j -2.+2.j -2.+0.j -2.-2.j]


In [1]:
# Function 5 : np.testing()

# The numpy.testing module provides utilities for testing numerical code, ensuring that arrays and mathematical results 
# are correct. These functions are useful when writing unit tests for scientific computing, machine learning, 
# and data science projects.

# Example 1: 
import numpy.testing as npt

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

# Test if arr1 and arr2 are identical
print(npt.assert_array_equal(arr1, arr2))

print("Test Passed Arrays are exactly the same!")


# Example 2: 
# Works best for floating-point comparisons, where precision errors can occur.
arr1 = np.array([1.000001, 2.00001, 3.000001])
arr2 = np.array([1.0, 2.0, 3.0])

# Test if arr1 and arr2 are nearly equal (default decimal precision = 6)
npt.assert_array_almost_equal(arr1, arr2, decimal=5)

print("Test Passed Arrays are nearly equal!")

# Example 3:
def divide(a, b):
    return a / b  # This will raise an error if b = 0

# Check if dividing by zero raises a ZeroDivisionError
with npt.assert_raises(ZeroDivisionError):
    divide(1, 0)  # This should raise an error

print("Test Passed Function correctly raises ZeroDivisionError!")


NameError: name 'np' is not defined