#### Q1: Convert a 1D array to a 2D array with 2 rows

In [2]:
import numpy as np

arr = np.arange(10)  
arr_2d = arr.reshape(2, -1)
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


####  Q2: Get the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common = np.intersect1d(a, b)
print(common)  


[2 4]


#### Q3: Get all items between 5 and 10 from a

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

result = a[(a >= 5) & (a <= 10)]
print(result)  


[ 6  9 10]


####  Q4: Limit number of items printed in array a to 6 elements

In [18]:
a = np.arange(20)

print(np.random.choice(a, 6)) 


[18  7 12 10 17  8]
